version: "3"
services:
  node:
    image: "node:latest"
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    expose:
      - "8081"
    #command: "npm start"
networks:
  default:
    external:
      name: pr-promotions
